# 사용할 베이스 이미지
FROM jenkins/jenkins:latest

# 환경 변수 설정
ENV DATABASE_URL=jdbc:mysql://localhost:3306/mydatabase
ENV API_KEY=your_api_key_here
ENV DEBUG=true
ENV PORT=8080
ENV LOG_LEVEL=debug
ENV TZ=Asia/Seoul

# Jenkins 플러그인 설치 예시 (선택적)
RUN /usr/local/bin/install-plugins.sh git matrix-auth

# Jenkins 설정 파일 복사 (선택적)
#  Jenkins 설정 파일(config.xml)을 호스트 파일 시스템에서 컨테이너 내의 특정 경로(/var/jenkins_home/config.xml)로 복사
COPY config.xml /var/jenkins_home/config.xml

# 필요한 추가 설정 및 명령어 실행
...

# Jenkins 실행 명령어 (기본적으로 jenkins 사용자로 실행됨)
USER team5