pipeline {
    agent {
        kubernetes {
            cloud 'team5-eks'
            yaml """
            apiVersion: v1
            kind: Pod
            spec:
              securityContext:
                runAsUser: 0
                runAsGroup: 0
                fsGroup: 0
              containers:
              - name: python
                image: python:3.9-slim
                tty: true
                volumeMounts:
                - name: workspace-volume
                  mountPath: /home/jenkins/agent
              volumes:
              - name: workspace-volume
                emptyDir: {}
            """
        }
    }

    environment {
        APP_NAME = "flask-app"
        RELEASE = "1.0.0"
        DOCKER_USER = "ksi05298"
        DOCKER_PASS = credentials('pjt-dockerhubtoken') // Jenkins Credentials에 저장된 Docker Hub 자격증명 ID
        IMAGE_NAME = "${DOCKER_USER}/${APP_NAME}"
        IMAGE_TAG = "${RELEASE}-${BUILD_NUMBER}"
    }

    stages {
        stage("Checkout from SCM") {
            steps {
                script {
                    sh 'pwd'
                    sh 'ls -al'
                    sh 'ls -al test-python'
                    git branch: 'pjt', credentialsId: 'pjt-githubtoken', url: 'https://github.com/ciscocloud03-team5/code-integration'
                    sh 'ls -al'
                    sh 'ls -al test-python'
                }
            }
        }

        stage('Run Tests') {
            steps {
                container('python') {
                    script {
                        dir('/home/jenkins/agent/workspace/test-python/test-python') {
                            sh '''
                            pwd
                            ls -al
                            python -m venv venv
                            . venv/bin/activate
                            pip install -r requirements.txt
                            pytest
                            '''
                        }
                    }
                }
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    dir('/home/jenkins/agent/workspace/test-python/test-python') {
                        docker.withRegistry('',DOCKER_PASS) {
                            docker_image = docker.build "${IMAGE_NAME}"
                        }

                        docker.withRegistry('',DOCKER_PASS) {
                            docker_image.push("${IMAGE_TAG}")
                            docker_image.push('latest')
                        }
                    }
                }
            }
        }
    }
}
